# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Interface\Controller\:
        resource: '../src/Interface/Controller'
        tags: ['controller.service_arguments']
        public: true

    App\Domain\Service\NotificationServiceInterface:
        alias: App\Infrastructure\Service\NotificationService
        public: true

    App\Application\UseCase\CreateClient\CreateClientHandler:
        tags: ['messenger.message_handler']

    App\Application\UseCase\UpdateClient\UpdateClientHandler:
        tags: ['messenger.message_handler']

    App\Application\UseCase\NotifyClient\NotifyClientHandler:
        tags: ['messenger.message_handler']

    App\Application\UseCase\GetClient\GetClientHandler:
        tags: ['messenger.message_handler']

    App\Application\UseCase\GetAllClients\GetAllClientsHandler:
        tags: ['messenger.message_handler']
